[package]
name = "hooker"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"
pcap = "1.0.0"
byteorder = "1.4"
ts3-query = "0.3.2"
tokio = { version = "1", features = ["full"] }
colored = "2.0.0"
